Repository Intro-to-SE-Lab-Fall-21/Group08, pull requests merged in 2021-10, with the labels that each got.

#23 Sequence Diagrams #6, #7 #8 #17
  Compose_new_Email.drawio.png
  Editing_Email_Drafts.drawio.png
  Login_for_the_first_time.drawio.png
  Logout.drawio.png
Labels: documentation

#30 Added sequence diagrams and class diagrams (#22)
  docs/Attaching_Documents_to_Draft.png
  docs/Browsing_Emails.png
  docs/Class_Diagram.png
Labels: documentation

#35 Added browsing email feature #10
  app.py
  templates/inbox.html
  templates/message.html
Labels: enhancement

#44 Added functionality for editing emails #8 and attaching files to emails #9
  composition.html
  main.py
Labels: enhancement, user story, feature

#59 Refactored and Updated installing, running, and testing
  .github/workflows/main.yml
  MAINFEST.in
  app.py
  readme.md
  requirements.txt
  setup.py
  tests.py
Labels: documentation
